Changed file Dockerfile with following changes:
diff --git a/express-kind-node-pty/Dockerfile b/express-kind-node-pty/Dockerfile
index b35c72d..3569eb9 100644
--- a/express-kind-node-pty/Dockerfile
+++ b/express-kind-node-pty/Dockerfile
@@ -72,10 +72,10 @@ RUN echo '#!/bin/bash' > /start.sh && \
     echo '    timeout=$((timeout-5))' >> /start.sh && \
     echo 'done' >> /start.sh && \
     echo '' >> /start.sh && \
-    echo 'if [ $timeout -le 0 ]; then' >> /start.sh && \
-    echo '    echo "ERROR: Docker daemon failed to start"' >> /start.sh && \
-    echo '    exit 1' >> /start.sh && \
-    echo 'fi' >> /start.sh && \
+    # echo 'if [ $timeout -le 0 ]; then' >> /start.sh && \
+    # echo '    echo "ERROR: Docker daemon failed to start"' >> /start.sh && \
+    # echo '    exit 1' >> /start.sh && \
+    # echo 'fi' >> /start.sh && \
     echo '' >> /start.sh && \
     echo 'echo "Starting Express server..."' >> /start.sh && \
     echo 'cd /app' >> /start.sh && \

diff --git a/express-kind-node-pty/Dockerfile b/express-kind-node-pty/Dockerfile
--- a/express-kind-node-pty/Dockerfile
+++ b/express-kind-node-pty/Dockerfile
@@ -72,10 +72,10 @@ RUN echo '#!/bin/bash' > /start.sh && \
     echo '    timeout=$((timeout-5))' >> /start.sh && \
     echo 'done' >> /start.sh && \
     echo '' >> /start.sh && \
-    echo 'if [ $timeout -le 0 ]; then' >> /start.sh && \
-    echo '    echo "ERROR: Docker daemon failed to start"' >> /start.sh && \
-    echo '    exit 1' >> /start.sh && \
-    echo 'fi' >> /start.sh && \
+    # echo 'if [ $timeout -le 0 ]; then' >> /start.sh && \
+    # echo '    echo "ERROR: Docker daemon failed to start"' >> /start.sh && \
+    # echo '    exit 1' >> /start.sh && \
+    # echo 'fi' >> /start.sh && \
     echo '' >> /start.sh && \
     echo 'echo "Starting Express server..."' >> /start.sh && \
     echo 'cd /app' >> /start.sh && \
